FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /app

COPY pom.xml ./
COPY transactions/pom.xml transactions/
COPY transactions/src transactions/src
COPY transactions/src/main/resources transactions/src/main/resources

RUN mvn -f transactions/pom.xml clean package

FROM openjdk:17-jdk-slim
WORKDIR /app

COPY --from=build /app/transactions/target/transactions-*.jar transactions.jar
EXPOSE 8081

CMD ["java","-jar","transactions.jar"]


