trigger:
  branches:
    include:
      - main  # or master branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'banking'  # Name of the Docker image
  registry: '<your-acr-name>.azurecr.io'
  serviceConnection: '<your-service-connection>'
  containerRegistry: '<your-acr-name>.azurecr.io'
  appServiceName: '<your-app-service-name>'
  resourceGroupName: '<your-resource-group>'

steps:

  - task: Checkout@1

  - task: Docker@2
    displayName: 'Login to ACR'
    inputs:
      command: login
      containerRegistry: $(serviceConnection)

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      dockerfile: '**/docker-compose.yml'  # Path to the Dockerfile in your repository
      tags: |
        $(registry)/$(imageName):$(Build.BuildId)

  - task: Docker@2
    displayName: 'Push Docker image to ACR'
    inputs:
      command: push
      tags: |
        $(registry)/$(imageName):$(Build.BuildId)

  - task: AzureWebAppContainer@2
    displayName: 'Deploy to Azure App Service'
    inputs:
      azureSubscription: $(serviceConnection)
      appName: $(appServiceName)
      resourceGroupName: $(resourceGroupName)
      dockerRegistryConnection: $(serviceConnection)
      imageName: $(registry)/$(imageName):$(Build.BuildId)
      configurationStrings: '-DOCKER_CUSTOM_IMAGE_NAME=$(registry)/$(imageName):$(Build.BuildId)'
      containerCommand: 'docker compose up'