name: accounts and transaction pipeline

on:
  push:
    branches:
      - feature/accounts  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'   
    - name: Docker Build
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      run: docker build -t springboot-app:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Install SSH key for access to local machine
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}

    # Step 2: Deploy to local machine (stop, pull image, start new container)
    - name: Deploy app via SSH
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /path/to/your/dockerized-app
          git pull origin main
          docker stop springboot-container || true
          docker rm springboot-container || true
          docker build -t springboot-app:latest .
          docker run -d --name springboot-container -p 8080:8080 springboot-app:latest
        EOF
